# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-23 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.IntegerField(max_length=2)),
                ('Qualification', models.CharField(max_length=200)),
                ('DateOfBirth', models.DateField()),
                ('Email', models.EmailField(max_length=150)),
                ('AboutMe', models.TextField(max_length=1000)),
            ],
        ),
    ]
