# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-23 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submitresume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Age',
            field=models.PositiveIntegerField(),
        ),
    ]
