# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-23 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submitresume', '0003_auto_20170923_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumes',
            name='DateOfBirth',
        ),
    ]
