# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-23 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submitresume', '0004_remove_resumes_dateofbirth'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resumes',
            new_name='Resume',
        ),
    ]
