# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-23 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submitresume', '0005_auto_20170923_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='AboutMe',
            new_name='About_Me',
        ),
    ]
