# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-24 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submitresume', '0006_auto_20170923_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
