# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-26 02:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submitresume', '0007_resume_is_rejected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='is_rejected',
            new_name='is_selected',
        ),
    ]
