# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-26 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submitresume', '0008_auto_20170926_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='Phone_number',
            field=models.PositiveIntegerField(default=7598528295, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='Skills',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='Age',
            field=models.PositiveIntegerField(max_length=2),
        ),
    ]
